spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test1;MODE=MYSQL
    username: local
    password:
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

      boot:
        model:
          naming:
            PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
